-- Persist the agent's --draft hint on pending_prs (review fix).
--
-- Pre-fix, the CLI accepted --draft but discarded it: the schema had
-- no column for it, the JSON shape didn't surface it, and the overlay
-- initialized its checkbox to a hard-coded false. An agent that
-- queued a PR specifically as draft (because the work isn't ready
-- for review) would see the user open it ready-for-review unless
-- they happened to re-check the box.
--
-- Persist the hint at queue time. The submit handler still accepts
-- a `draft` field on the POST body so the user can flip it before
-- approval — the row's value is just the default the overlay
-- initializes its checkbox from.
ALTER TABLE pending_prs ADD COLUMN draft INTEGER NOT NULL DEFAULT 0;
