-- Capture the agent's drafted review verdict (APPROVE / REQUEST_CHANGES /
-- COMMENT) so SKY-205's writer can detect when the human changed it
-- before submitting. SKY-204 added `original_review_body` for the
-- review body but missed the parallel for `review_event` — and the
-- review-edit endpoint (handleReviewUpdate in
-- internal/server/reviews_handler.go) lets the user mutate event in
-- place, so without an original we'd have no way to see "agent
-- drafted APPROVE, human submitted REQUEST_CHANGES" — exactly the
-- highest-signal datum the human-content workstream is meant to
-- preserve.
--
-- Nullable: pending_reviews rows mid-flight when this migration lands
-- (already had review_event set by SetPendingReviewSubmission before
-- this column existed) get NULL. The diff formatter degrades when
-- it sees NULL — it just emits the final verdict without an
-- unchanged/changed annotation, which is the honest answer ("we
-- don't know what the agent drafted").
ALTER TABLE pending_reviews ADD COLUMN original_review_event TEXT;
